final int mcVersion = {
    def s = project.minecraft_version.split('\\.')
    int v = s[0].toInteger() * 10000 + s[1].toInteger() * 100
    s.length >= 3 ? v + s[2].toInteger() : v
}.call()
final boolean unobfuscated = mcVersion >= 26_00_00

apply plugin: unobfuscated ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'
apply plugin: 'com.replaymod.preprocess'

configurations {
    modRuntimeOnly.exclude group: 'net.fabricmc', module: 'fabric-loader'
}

repositories {
    mavenLocal()
    maven {
        url = "https://masa.dy.fi/maven/sakura-ryoko"
        content {
            includeGroupAndSubgroups("fi.dy.masa")
        }
    }
    maven {
        url = "https://maven.fallenbreath.me/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    if (!unobfuscated) {
        mappings loom.layered() {
            officialMojangMappings()
        }
    }
    def autoImplementation = {
        dep -> unobfuscated ? implementation(dep) : modImplementation(dep)
    }
    autoImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    autoImplementation "fi.dy.masa.malilib:malilib-fabric-${project.malilib_version}"
    autoImplementation "fi.dy.masa.litematica:litematica-fabric-${project.litematica_version}"
}

JavaVersion JAVA_VERSION

if (mcVersion >= 260000) {
    JAVA_VERSION = JavaVersion.VERSION_25
} else if (mcVersion >= 12100) {
    JAVA_VERSION = JavaVersion.VERSION_21
}

java {
    sourceCompatibility = JAVA_VERSION
    targetCompatibility = JAVA_VERSION
}

String fullModVersion = "v${project.mod_version}-mc${project.minecraft_version}"

base {
    archivesName.set("downmatica-${fullModVersion}")
}

jar {
    from("LICENSE")
}

processResources {
    filesMatching("fabric.mod.json") {
        expand ([
                "version": fullModVersion,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}