plugins {
    id 'maven-publish'
}

final boolean unobfuscated = mcVersion >= 26_00_00

apply plugin: unobfuscated ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'
apply plugin: 'com.replaymod.preprocess'

repositories {
    mavenLocal()
    maven {
        url = "https://masa.dy.fi/maven/sakura-ryoko"
    }
    maven {
        url = "https://maven.fallenbreath.me/releases"
    }
    maven {
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    if (!unobfuscated) {
        mappings loom.layered() {
            officialMojangMappings()
        }
    }
    def autoImplementation = {
        dep -> unobfuscated ? implementation(dep) : modImplementation(dep)
    }
    autoImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    autoImplementation "fi.dy.masa.malilib:malilib-fabric-${project.malilib_version}"
    def autoCompileOnly = {
        dep -> unobfuscated ? compileOnly(dep) : modCompileOnly(dep)
    }
    autoCompileOnly "fi.dy.masa.litematica:litematica-fabric-${project.litematica_version}"
    autoCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
    autoCompileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    def autoRuntimeOnly = {
        dep -> unobfuscated ? runtimeOnly(dep) : modRuntimeOnly(dep)
    }
    autoRuntimeOnly "fi.dy.masa.litematica:litematica-fabric-${project.litematica_version}"
    autoRuntimeOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
    autoRuntimeOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

JavaVersion JAVA_VERSION

if (mcVersion >= 260000) {
    JAVA_VERSION = JavaVersion.VERSION_25
} else if (mcVersion >= 12100) {
    JAVA_VERSION = JavaVersion.VERSION_21
}

java {
    sourceCompatibility = JAVA_VERSION
    targetCompatibility = JAVA_VERSION
    withSourcesJar()
}

group = "top.ajitech"
version = "v${project.mod_version}-mc${project.minecraft_version}"

base {
    archivesName.set("downmatica")
}

jar {
    from("LICENSE")
}

processResources {
    filesMatching("fabric.mod.json") {
        expand ([
                "version": version,
                "minecraft_version": project.minecraft_version,
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "downmatica"
        }
    }
    repositories {
        maven {
            url = "https://maven.ajitech.top/releases"
            credentials(PasswordCredentials) {
                username = 'aji'
                password = System.getenv("AJI_MAVEN_TOKEN_PASSWORD")
            }
        }
    }
}